# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 2000
scan_timeout = 100

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$container\
$terraform\
$nix_shell\
$azure\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$shell\
$character"""

[directory]
style = "#cc44ff bold"

[sudo]
disabled = false
symbol = "🔓"

[git_branch]
style = "green bold"

[gcloud]
disabled = true
